### ISSUE TITLE
입력 시, 트리 출력

### ISSUE THREAD

**Issue by jqkk** [jqkk/folderpocket#1]
## 🔍 Issue
Input 창에 입력을 하면 Output으로 폴더 구조가 출력됩니다. 

## ✅ To-do

- [x] Input 컴포넌트 제작
- [x] Output or Tree 컴포넌트 제작
- [x] 입력을 폴더 구조로 변환하는 로직 구현
